### ISSUE TITLE
[1.15.2] Crashes in SMP

### ISSUE THREAD

**Issue by mr-poyo** [IchHabeHunger54/PotionBundles#2]
Version: potionbundles-1.1.jar
Forge: 31.2.0

Runs fine in single player, but server crashes:

Crash Log: https://pastebin.com/p1e8MwyP

**Comment by IchHabeHunger54** [comment]
Sorry for the late response, had other stuff to do.

Please provide debug.log, and not only the crash report. Also, when did it crash (startup, crafting, using, ...)?

**Comment by mr-poyo** [comment]
This crash happens on SMP startup. Server won't load.

Latest.log: https://pastebin.com/D167sguT
Another crash report: https://pastebin.com/16vjHTrn
Partial debug.log (end bit): https://pastebin.com/kpJjdFiq

I am unable to paste the whole debug.log as it's too large of a log even when I generate a fresh one. Hope this helps!

**Comment by IchHabeHunger54** [comment]
Try removing all other mods and starting the server with only the potion bundles mod. If that works, put in the other mods one at a time, and tell me which of the other mods crashes with this one. If that doesnt work, send me the log again, but only with the potion bundles mod. Because then, it is clearly a mistake I made myself.

**Comment by mr-poyo** [comment]
My apologies, I don't have another server to test this with. My current server/pack is in mid-development, and I unfortunately can't remove them at this time. If I ever prepare another server world I'll be sure to test this mod alone in SMP prior to starting. If the issues occurs again, I'll reopen the issue at that time. Thanks!
